version: '3.9'

services:

  backend:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    container_name: hack-backend
    env_file:
      - .env
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hack-backend.rule=Host(`api-hack.energy-cerber.ru`)"
      - "traefik.http.routers.hack-backend.entrypoints=websecure"
      - "traefik.http.routers.hack-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.hack-backend.loadbalancer.server.port=8000"
    volumes:
      - ./backend/assets:/app/assets
    networks:
      - my_network
    ports:
      - "8000"

  postgres:
    container_name: hack-db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - my_network

networks:
  my_network:
    external: true
    name: todo-prod_my_network
