version: '3.9'

services:

  frontend:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    container_name: hack-frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - network

  backend:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    container_name: hack-backend
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./backend/assets:/app/assets
    networks:
      - network

  postgres:
    container_name: hack-db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - network

networks:
  network:
